In [ ]:
/lis=['A','B','C']
print(lis)

['A', 'B', 'C']


In [ ]:
lis=['A','B','C']
print(lis[2])

C


In [ ]:
lis=['A','B','C']
print(lis[-1])

C


In [ ]:
lis=['A','B','C']
lis.insert(1,'KARTHIK')
print(lis)

['A', 'KARTHIK', 'B', 'C']


In [ ]:
lis=['A','B','C']
lis.append('KARTHIK')
print(lis)

['A', 'B', 'C', 'KARTHIK']


In [ ]:
lis=['A','B','C','KARTHIK']
lis.remove('KARTHIK')
print(lis)

['A', 'B', 'C']


In [ ]:
lis=['A','B','C','KARTHIK']
lis.pop(2)
print(lis)

['A', 'B', 'KARTHIK']


In [ ]:
lis=['A','B','C','KARTHIK']
lis.pop()
print(lis)

['A', 'B', 'C']


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)

(2, 4)


In [ ]:
np.random.random(5)
np.ones((4,3,2,4,3))

array([[[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]],



       [[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        

In [ ]:
a=([1,2,3,4],[5,6,7,8])
for x in np.nditer(a):
  print(x)


(array(1), array(5))
(array(2), array(6))
(array(3), array(7))
(array(4), array(8))


In [ ]:
# Python Programming illustrating
# numpy.linspace method

import numpy as geek

# restep set to True
print("B\n", geek.linspace(2.0, 3.0, num=5, retstep=False), "\n")

# To evaluate sin() in long range
x = geek.linspace(0, 2, 10,retstep=True)
print("A\n", x)


B
 [2.   2.25 2.5  2.75 3.  ] 

A
 (array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ]), 0.2222222222222222)


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[0:3,0])


[1 4]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:4,1])


[2 5 8]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:4,1:3])


[[2 3]
 [5 6]
 [8 9]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[2:4,0:3])


[[7 8 9]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
r=a[1:2]
print(r)
print(r.shape)

[[4 5 6]]
(1, 3)


In [ ]:
import numpy as np
a=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])
b=a[1:2,:]
c=a[1:3,:]
print(a.shape)
print(b.shape)
print(c.shape)


(3, 4)
(1, 4)
(2, 4)


In [ ]:

a=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12],[13,14,15,16]])
b=np.array([0,2,1,3])
print(a[np.arange(4),b])




[ 1  6  8 16]


In [ ]:

a=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12],[13,14,15,16]])
print(np.argmax(a,axis=1))




[3 3 3 3]


In [ ]:
a=[1,2,3,4]
#a=np.append(a,([5,6,7,8]))
print(a)
b=[9,14,43,32]
res=np.vstack((a,b))
print(res)


[1, 2, 3, 4]
[[ 1  2  3  4]
 [ 9 14 43 32]]


In [ ]:
a=np.array([1,2])
b=np.array([3,4])
print(a.dot(b))
print(np.dot(a,b))


11
11


In [ ]:
a=np.array([[1,6],[5,6]])
b=np.array([[5,4],[88,77]])
c=a.dot(b)
d=np.dot(a,b)
print(c,d)
k=np.transpose(a)
j=np.transpose(b)
print(k.dot(j))


[[533 466]
 [553 482]] [[533 466]
 [553 482]]
[[ 25 473]
 [ 54 990]]


In [ ]:
a=np.array([1,2])
b=a.squeeze()
print(b)

[1 2]


In [ ]:
a=np.array([1,2].)